# Generated by Django 5.2.2 on 2025-06-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="StockData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company_symbol", models.CharField(db_index=True, max_length=10)),
                ("date", models.DateField()),
                ("open", models.DecimalField(decimal_places=2, max_digits=10)),
                ("high", models.DecimalField(decimal_places=2, max_digits=10)),
                ("low", models.DecimalField(decimal_places=2, max_digits=10)),
                ("close", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.BigIntegerField()),
                ("file_source", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ohlc_data",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["company_symbol", "date"],
                        name="ohlc_data_company_8c1fb6_idx",
                    ),
                    models.Index(fields=["date"], name="ohlc_data_date_639daa_idx"),
                ],
                "unique_together": {("company_symbol", "date")},
            },
        ),
    ]
