# Generated by Django 5.2.2 on 2025-06-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="company",
            table="stocks_company",
        ),
    ]
